#############################################################################
# Makefile for building: hw8.app/Contents/MacOS/hw8
# Generated by qmake (2.01a) (Qt 4.8.6) on: Fri Apr 24 17:22:43 2015
# Project:  hw8.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile hw8.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.6/include -I. -I. -F/usr/local/Cellar/qt/4.8.6/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.6/lib -L/usr/local/Cellar/qt/4.8.6/lib -framework QtGui -L/usr/local/Cellar/qt/4.8.6/lib -F/usr/local/Cellar/qt/4.8.6/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ar.cpp \
		book.cpp \
		clothing.cpp \
		db_parser.cpp \
		m.cpp \
		movie.cpp \
		mw.cpp \
		product.cpp \
		product_parser.cpp \
		store.cpp \
		user.cpp \
		util.cpp \
		viewcart.cpp moc_ar.cpp \
		moc_mw.cpp \
		moc_viewcart.cpp
OBJECTS       = ar.o \
		book.o \
		clothing.o \
		db_parser.o \
		m.o \
		movie.o \
		mw.o \
		product.o \
		product_parser.o \
		store.o \
		user.o \
		util.o \
		viewcart.o \
		moc_ar.o \
		moc_mw.o \
		moc_viewcart.o
DIST          = /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf \
		hw8.pro
QMAKE_TARGET  = hw8
DESTDIR       = 
TARGET        = hw8.app/Contents/MacOS/hw8

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile hw8.app/Contents/PkgInfo hw8.app/Contents/Resources/empty.lproj hw8.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) hw8.app/Contents/MacOS/ || $(MKDIR) hw8.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hw8.pro  /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile hw8.pro
/usr/local/Cellar/qt/4.8.6/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.6/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.6/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.6/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.6/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile hw8.pro

hw8.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) hw8.app/Contents || $(MKDIR) hw8.app/Contents 
	@$(DEL_FILE) hw8.app/Contents/PkgInfo
	@echo "APPL????" >hw8.app/Contents/PkgInfo
hw8.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) hw8.app/Contents/Resources || $(MKDIR) hw8.app/Contents/Resources 
	@touch hw8.app/Contents/Resources/empty.lproj
	
hw8.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) hw8.app/Contents || $(MKDIR) hw8.app/Contents 
	@$(DEL_FILE) hw8.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,hw8,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.6/mkspecs/unsupported/macx-clang-libc++/Info.plist.app >hw8.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/hw81.0.0 || $(MKDIR) .tmp/hw81.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hw81.0.0/ && $(COPY_FILE) --parents ar.h book.h clothing.h datastore.h db_parser.h movie.h msort.h mw.h product.h product_parser.h review.h store.h user.h util.h viewcart.h .tmp/hw81.0.0/ && $(COPY_FILE) --parents ar.cpp book.cpp clothing.cpp db_parser.cpp m.cpp movie.cpp mw.cpp product.cpp product_parser.cpp store.cpp user.cpp util.cpp viewcart.cpp .tmp/hw81.0.0/ && (cd `dirname .tmp/hw81.0.0` && $(TAR) hw81.0.0.tar hw81.0.0 && $(COMPRESS) hw81.0.0.tar) && $(MOVE) `dirname .tmp/hw81.0.0`/hw81.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hw81.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r hw8.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_ar.cpp moc_mw.cpp moc_viewcart.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ar.cpp moc_mw.cpp moc_viewcart.cpp
moc_ar.cpp: review.h \
		datastore.h \
		product.h \
		user.h \
		ar.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ar.h -o moc_ar.cpp

moc_mw.cpp: db_parser.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		product_parser.h \
		util.h \
		store.h \
		msort.h \
		ar.h \
		mw.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mw.h -o moc_mw.cpp

moc_viewcart.cpp: mw.h \
		db_parser.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		product_parser.h \
		util.h \
		store.h \
		msort.h \
		ar.h \
		viewcart.h
	/usr/local/Cellar/qt/4.8.6/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ viewcart.h -o moc_viewcart.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

ar.o: ar.cpp ar.h \
		review.h \
		datastore.h \
		product.h \
		user.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ar.o ar.cpp

book.o: book.cpp book.h \
		product.h \
		review.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book.o book.cpp

clothing.o: clothing.cpp util.h \
		clothing.h \
		product.h \
		review.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clothing.o clothing.cpp

db_parser.o: db_parser.cpp db_parser.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		product_parser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_parser.o db_parser.cpp

m.o: m.cpp mw.h \
		db_parser.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		product_parser.h \
		util.h \
		store.h \
		msort.h \
		ar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o m.o m.cpp

movie.o: movie.cpp util.h \
		movie.h \
		product.h \
		review.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o movie.o movie.cpp

mw.o: mw.cpp mw.h \
		db_parser.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		product_parser.h \
		util.h \
		store.h \
		msort.h \
		ar.h \
		viewcart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mw.o mw.cpp

product.o: product.cpp product.h \
		review.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product.o product.cpp

product_parser.o: product_parser.cpp product_parser.h \
		product.h \
		review.h \
		book.h \
		clothing.h \
		movie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o product_parser.o product_parser.cpp

store.o: store.cpp store.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		db_parser.h \
		product_parser.h \
		book.h \
		clothing.h \
		movie.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o store.o store.cpp

user.o: user.cpp user.h \
		product.h \
		review.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

util.o: util.cpp util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

viewcart.o: viewcart.cpp mw.h \
		db_parser.h \
		datastore.h \
		product.h \
		review.h \
		user.h \
		product_parser.h \
		util.h \
		store.h \
		msort.h \
		ar.h \
		viewcart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewcart.o viewcart.cpp

moc_ar.o: moc_ar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ar.o moc_ar.cpp

moc_mw.o: moc_mw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mw.o moc_mw.cpp

moc_viewcart.o: moc_viewcart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewcart.o moc_viewcart.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

